import PostGroup from "@/components/PostGroup";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "@/utils/trpc";

const Home: NextPage = () => {
  const x=trpc.hello.useQuery({text:'hosse!'})
  console.log(x.data)

  return (
    <>
      <Head>
        <title>Csv Uploader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen h-full  bg-black flex flex-col ">
          <div className="h-20 w-full flex items-center  justify-between px-4 ">
          <svg
            width="34"
            height="27"
            viewBox="0 0 34 27"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M3.09091 0H15.4545V3H3.09091V21H15.4545V3H18.5455V21H30.9091V3H18.5455V0H34V24H18.5455V27H15.4545V24H0V0H3.09091ZM27.8182 10.5H21.6364V13.5H27.8182V10.5ZM21.6364 6H27.8182V9H21.6364V6ZM24.7273 15H21.6364V18H24.7273V15Z"
              fill="#7E7E7E"
            />
          </svg>

          <select
            id="countries"
            className="block h-4  w-28   rounded-sm bg-[#7E7E7E] p-2.5 text-sm "
          >
            <option selected></option>
            <option value="US">Economy</option>
            <option value="CA">Policy</option>
            <option value="FR">Corporate</option>
            <option value="DE">Markets</option>
            <option value="DE">Investments</option>

          </select>
          </div>
        <div className="p-1 w-full flex-grow  flex">
          <div className="bg-[#7e7e7e] w-full md:w-10/12  md:ml-auto md:mr-2  px-1  md:px-2 py-2 md:py-1 rounded-md ">
            <PostGroup/>
          </div>

        </div>
      </main>
    </>
  );
};

export default Home;

/* 
<div className="flex h-20 w-full items-center  justify-between px-4 bg-blue-400">
          <svg
            width="34"
            height="27"
            viewBox="0 0 34 27"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M3.09091 0H15.4545V3H3.09091V21H15.4545V3H18.5455V21H30.9091V3H18.5455V0H34V24H18.5455V27H15.4545V24H0V0H3.09091ZM27.8182 10.5H21.6364V13.5H27.8182V10.5ZM21.6364 6H27.8182V9H21.6364V6ZM24.7273 15H21.6364V18H24.7273V15Z"
              fill="#7E7E7E"
            />
          </svg>

          <select
            id="countries"
            className="block h-4  w-28   rounded-sm bg-[#7E7E7E] p-2.5 text-sm "
          >
            <option selected></option>
            <option value="US">Economy</option>
            <option value="CA">Policy</option>
            <option value="FR">Corporate</option>
            <option value="DE">Markets</option>
            <option value="DE">Investments</option>

          </select>
        </div>
         */